# Generated by Django 4.2.11 on 2024-05-02 18:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('test_ids', models.TextField()),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('topic', models.CharField(max_length=50)),
                ('validity', models.CharField(default='Unapproved', max_length=50)),
                ('label', models.CharField(default='Unacceptable', max_length=20)),
                ('ground_truth', models.CharField(default='Unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Perturbation',
            fields=[
                ('label', models.CharField(default='Unacceptable', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('type', models.CharField(default='spelling', max_length=20)),
                ('validity', models.CharField(default='Unapproved', max_length=50)),
                ('ground_truth', models.CharField(default='Unknown', max_length=20)),
                ('test_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
            ],
        ),
    ]
