# Generated by Django 4.2.9 on 2024-02-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('topic', models.CharField(max_length=50)),
                ('validity', models.CharField(max_length=50)),
            ],
        ),
    ]
