# Generated by Django 4.2.10 on 2024-04-15 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('essay', models.CharField(max_length=50)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('topic', models.CharField(max_length=50)),
                ('validity', models.CharField(default='Unapproved', max_length=50)),
                ('label', models.CharField(default='Unacceptable', max_length=20)),
            ],
        ),
    ]
