# Generated by Django 4.2.9 on 2024-02-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='label',
            field=models.CharField(default='Unacceptable', max_length=20),
        ),
    ]
