# Generated by Django 4.2.10 on 2024-02-26 19:38

from django.db import migrations
from core.ada import *

def create_data(apps, schema_editor):
    Test = apps.get_model('core', 'Test')
    obj = create_obj()

    data = obj.df

    for index, row in data.iterrows():
        obj = Test(id=index, title=row['input'], topic = row['topic'], label = row['output'])
        if Test.objects.filter(title=obj.title).exists(): # does not work with get
            pass
        else: 
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]