# Generated by Django 4.2.10 on 2024-04-20 23:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perturbation',
            fields=[
                ('test_parent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.test')),
                ('label', models.CharField(default='Unacceptable', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.TextField()),
            ],
        ),
    ]
